def l():
    print('--------------------------')
    """
  feito para dar algumas linhas
  """

# Exercício 1:
# Verifique se o número 10 é igual ao número 20 e armazene o resultado em uma variável booleana. Imprima o resultado.
# l()
# a = 10
# b = 20
# resultado = (a == b)
# print(f'{resultado}')
# l()

# Exercício 2:
# Crie duas strings com o valor "Olá" e verifique se elas são iguais usando o operador ==. Armazene o resultado em uma variável booleana e imprima o resultado.

# l()
# a = ('ola')
# b = ('ola')
# resultado = (a == b)
# print(f'{resultado}')
# l()

# Exercício 3:
# Compare duas variáveis booleanas, uma com o valor True e outra com o valor False, para verificar se são iguais. Armazene o resultado e imprima-o.

# l()
# a1 = 10
# b1 = 10
# resultado1 = (a1 == b1)

# a2 = 12
# b2 = 23
# resultado2 = (a2 == b2)

# total = (resultado1 == resultado2)

# print(f'{total}')
# l()

# Exercício 4:
# Crie duas listas [1, 2, 3] e compare-as para verificar se são iguais. Use o operador == e armazene o resultado em uma variável booleana, depois imprima o resultado.

# l()

# numero1 = [1,2,3,4,5]

# numero2 = [6,7,8,9,10]

# total = (numero1 == numero2)

# print(f'{total}')
# l()


# Exercício 5:
# Crie dois dicionários com o mesmo conteúdo {"chave": "valor"} e verifique se são iguais usando o operador ==. Armazene e imprima o resultado.
# l()
# nome_e_idade_1 = {'nome':'yan','idade':'10'}
# nome_e_idade_2 = {'nome':'yan','idade':'10'}

# total = (nome_e_idade_1 == nome_e_idade_2)

# print(total)
# l()


# Exercício 6:
# Compare um número inteiro 10 com uma string "10" usando o operador == e verifique se são iguais. Armazene o resultado em uma variável booleana e imprima o resultado.

# l()

# a1 = 10
# a2 = '10'
# total = (a1 == a2)

# print(f'{total}')
# l()

# Exercício 7:
# Verifique se o número 4 é par. Use o operador == para comparar se o resto da divisão por 2 é igual a 0. Armazene e imprima o resultado.
l()

a = 4

b = 3

c = a / b

if c % 2 == 0:
    print('é divisivel')
else:
    print('NÃO')
l()

# Exercício 8:
# Verifique se uma pessoa com 18 anos é maior de idade (18 anos ou mais). Use o operador >= e armazene o resultado em uma variável booleana, depois imprima o resultado.

# Exercício 9:
# Solicite ao usuário que digite dois valores. Compare esses valores para verificar se são iguais usando o operador ==. Armazene o resultado e imprima-o.

# Exercício 10:
# Compare o comprimento de duas strings, "Python" e "Java", para verificar se têm o mesmo comprimento. Use a função len() e o operador ==, armazene o resultado em uma variável booleana e imprima o resultado.
